### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by AlexZeitler** [thenativeweb/crew#4]
`crew` currently doesn't support tags for images.
When using `crew` with the official `Postgres` image, the workflow becomes a bit weird (looks like it's caused by the tagging strategy chosen by the `Postgres` image maintainers):

If you want to see if Docker has the image, you have to use `postgres`.
If you want download the latest image, you have to explicitely use `postgres:latest`, otherwise `crew`will download all tags of `postgres`.

So I would like to implement tag support for `crew`.

**Comment by goloroden** [comment]
This would be awesome :-)

Basically, I think, that if you do not specify anything, it should internally use `latest`, otherwise the tag specified.

What do you think about this?

**Comment by AlexZeitler** [comment]
Makes sense :+1:

**Comment by AlexZeitler** [comment]
How do you debug the tests?
Using WebStorm, breakpoints are ignored...

**Comment by goloroden** [comment]
Please don't laugh ... we're debugging them using `console.log` ;-)

**Comment by AlexZeitler** [comment]
Do you run the plain mochacli task then or do you modify the eslint settings to allow console output?

**Comment by goloroden** [comment]
`grunt test` should do the trick ;-)

**Comment by AlexZeitler** [comment]
That makes sense in so many ways :smile:

**Comment by AlexZeitler** [comment]
Tag support for downloadImage and hasImage is already done: https://github.com/AlexZeitler/crew.
Next is tag support for running containers.

**Comment by goloroden** [comment]
This is awesome, thanks for your great work :-)!

I'm really looking forward to your PR :-)!

**Comment by goloroden** [comment]
This one was resolved in a really, really great way by your PR … thank you so much for your great support :-)!

**Comment by AlexZeitler** [comment]
I'm glad that I could help :smile:
